# Generated by Django 2.2.6 on 2019-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbr', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='wanted_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Position'),
        ),
    ]
