# Generated by Django 2.2.6 on 2019-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('company_name', models.CharField(blank=True, max_length=140)),
                ('company_description', models.TextField()),
                ('site_link', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=12)),
                ('contact_email', models.EmailField(blank=True, max_length=32)),
            ],
        ),
    ]
