# Generated by Django 2.2.6 on 2019-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191126_2139'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', related_query_name='vacancy', to='employer.Employer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', related_query_name='vacancy', to='employee.Position')),
            ],
        ),
    ]
